### ISSUE TITLE
Is there a roadmap

### ISSUE THREAD

**Issue by changxiangzhong** [MiCode/MiBox_Kernel_OpenSource#1]
Do we have a plan to release the source code for other products? Such as mi3 enhanced? @zhangchen16

**Comment by zhangchen16** [comment]
could you please check the information of setting--> about -->build on your mi3 enhanced?  there are  different mi3 enhanced in different regions.

**Comment by changxiangzhong** [comment]
It was purchased in China. The model is 3-MDZ-18-AA, with a MTK processor

**Comment by zhangchen16** [comment]
no plan to oss that one by now
