### ISSUE TITLE
MITV 3 60'' kernel source

### ISSUE THREAD

**Issue by saalmaan** [MiCode/MiBox_Kernel_OpenSource#3]
Hi

Can you please release MITV 3 60'' (小米电视主机 (L60M4-AA) - https://www.mi.com/tvzj/)  kernel source code. Its been years since new update has arrived, very frustrating that we are stuck with Android 5.1. With the release of this Kernel source code, developers can at least bring latest Android TV to MITV 3 60'' and give this TV new lease of life.

Any update on this? @ivan19871002 mentioned on Weibo that MITV source kernel is coming soon, do you know any approximate dates? https://m.weibo.cn/detail/4341835327348409

@ivan19871002
https://github.com/MiCode/MiBox_Kernel_OpenSource is not for MiTV 60''. Or you are suggesting that MIBOX3(global) kernel can be used for MiTV 3 60''?

Thanks

**Comment by ivan19871002** [comment]
@zhangchen16  is  the project owner .

**Comment by zhangchen16** [comment]
抱歉，这款电视暂时没有开源计划呢
会先从在研项目开始推动开源，然后才会做老产品的开源

**Comment by saalmaan** [comment]
> 抱歉，这款电视暂时没有开源计划呢 (Sorry, this TV has no open source plan yet.)
> 会先从在研项目开始推动开源，然后才会做老产品的开源 (Will start to promote open source from the research project, and then do the open source of the old product.)

@zhangchen16  I tried to Google translate but the second point didn't make much sense. Did you say that you are planning to prioritise open sourcing kernels for newer TV first and then Old TV?  

Can you please give an estimated time by when we may get the kernel for MiTV 60''?
